version: "3.8"

services:
  tataru:
    image: tataru
    build: ./
    ports:
      - "8080:8080"
    environment:
      - SQL_DATABASE
      - SQL_USER
      - SQL_PASSWORD
      - SQL_HOST
      - DISCORD_TOKEN
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    user: ${POSTGRES_UID}:${POSTGRES_GID}
    volumes:
      - postgres_data:/postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=postgres
volumes:
  postgres_data:
